---
- name: Ensure .ssh/config.d exist
  file: path={{ssh_config_home}}/.ssh/config.d state=directory owner="{{ssh_config_user}}" group="{{ssh_config_group}}" mode=700

- name: ensure config for each host of the inventory exist
  template: src=inventory.j2 dest={{ssh_config_home}}/.ssh/config.d/{{ssh_config_order}}-{{hostvars[item].inventory_hostname_short}}
  when: item != 'localhost' and item != '127.0.0.1'
  with_items: groups.all
               
- name: assemble ssh config
  assemble: src={{ssh_config_home}}/.ssh/config.d dest={{ssh_config_home}}/.ssh/config
