Vagrant.configure("2") do |config|
  config.vm.define "ubuntu" do |ubuntu|
    ubuntu.vm.box = "ubuntu/xenial64"
    ubuntu.vm.hostname = "helper-ubuntu"
    ubuntu.vm.synced_folder ".", "/vagrant", disabled: true
    ubuntu.vm.provision "ansible" do |ansible|
      ansible.playbook = "playbook.yml"
      ansible.galaxy_role_file = '../test-requirements.yml'
      ansible.extra_vars = {
        operator_user: 'ubuntu'
      }
    end
  end
end
