---
- name: Playbook for role testing
  hosts: all
  connection: paramiko

  vars:
    ansible_ssh_user: dragon

    configure_adminer: yes
    configure_phpmyadmin: yes
    configure_rally: yes
    configure_sshconfig: yes

    adminer_groupname: ungrouped
    phpmyadmin_groupname: ungrouped
    rungroupedy_groupname: ungrouped
    sshconfig_groupname: ungrouped

  roles:
    - role: ansible-helper
